from typing import Protocol, runtime_checkable, Any
from image import BasicImage

@runtime_checkable
class CameraProtocol(Protocol):
    def __enter__(self) -> 'CameraProtocol': ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool | None: ...
    def capture(self) -> BasicImage: ...
